Acme\SecondBazBundle\Entity\Kategor:
    type: entity
    table: kategor
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
    manyToMany:
        idtovar:
            targetEntity: Tovar
            cascade: {  }
            fetch: LAZY
            mappedBy: idkategor
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
